### ISSUE TITLE
Feedback on NCHWC case study

### ISSUE THREAD

**Issue by lisaong** [MarinaHesham/HighPerfDL-Accera-Samples#1]
Thanks for contributing the case study! Here are some comments to consider:

https://github.com/marina-neseem/Accera-High-Perf-DL/blob/cc00659ba07dcd8159afcb4a64205ffa67cd4785/case_studies/nchwc_convolution_gridsearch/README.md?plain=1#L4

Comment: In the beginning of this case study, it'll be helpful to expand the acronym / symbols before diving into the details. For example, something like the bulletpoint list here (but feel free to explain it in a different way): https://stackoverflow.com/questions/37689423/convert-between-nhwc-and-nchw-in-tensorflow

https://github.com/marina-neseem/Accera-High-Perf-DL/blob/a0afaca5077cb211c3abdc617a408de35162d13f/case_studies/nchwc_convolution_gridsearch/README.md?plain=1#L1-L2

https://github.com/marina-neseem/Accera-High-Perf-DL/blob/cc00659ba07dcd8159afcb4a64205ffa67cd4785/case_studies/matmul_gridsearch_on_avx2/README.md?plain=1#L1-L2

Comment: can remove these headings, because this is a community case study and not part of the Accera repo. Once you've done that, the git SHA for the other file also needs to be updated in the TOC (you can piggyback on the PR you already have)

https://github.com/marina-neseem/Accera-High-Perf-DL/blob/cc00659ba07dcd8159afcb4a64205ffa67cd4785/case_studies/matmul_gridsearch_on_avx2/README.md?plain=1#L148

Comment: starting with v1.2.4, we've removed the need to specify the number of parameters as an argument. You can upgrade by doing this:
```
pip install --upgrade accera-llvm
pip install --upgrade accera-compilers
pip install --upgrade accera
```

And then replace `create_parameters(num)` with `create_parameters()`

https://github.com/marina-neseem/Accera-High-Perf-DL/blob/cc00659ba07dcd8159afcb4a64205ffa67cd4785/case_studies/nchwc_convolution_gridsearch/README.md?plain=1#L81

Comment: I'm trying to find more background on the correlation between 8/16, and AVX2/AVX512. Is this recommendation based on the width of the vector registers? If so, it will be helpful to add the reasoning.

https://github.com/marina-neseem/Accera-High-Perf-DL/blob/cc00659ba07dcd8159afcb4a64205ffa67cd4785/case_studies/nchwc_convolution_gridsearch/README.md?plain=1#L302

https://github.com/marina-neseem/Accera-High-Perf-DL/blob/cc00659ba07dcd8159afcb4a64205ffa67cd4785/case_studies/matmul_gridsearch_on_avx2/README.md?plain=1#L281

Comment: I missed this earlier. Should we add a requirements.txt file listing the dependencies for each case study? This will be self-documenting and tie each case study to a specific snapshot/version of Accera (so you don't have to keep on updating if we change the DSL).

For example, I think this will suffice:
```
accera==1.2.4
pandas
```

You can either do one `requirements.txt` in each folder (to track dependencies separately for each case study), or just one top level requirements.txt. Either is fine.

**Comment by lisaong** [comment]
Small correction on `requirements.txt`. To be safe we should list the versions of the sub-packages as well:

```
accera==1.2.4
accera-compilers==1.2.4
accera-llvm==1.2.4
pandas
```

**Comment by marina-neseem** [comment]
Sounds good, thanks Lisa!
I updated the requirements file.

**Comment by lisaong** [comment]
Thanks for the quick response! Once this fix is verified: https://github.com/microsoft/hat/pull/50, you'll also need to add an entry for hatlib to pull in this version or later:

```
hatlib>=0.0.15
```

**Comment by marina-neseem** [comment]
Done, thanks Lisa!

**Comment by lisaong** [comment]
Nice and succinct explanation on the choice of 8 vs. 16 for AVX2/AVX512!
