### ISSUE TITLE
Minor Feedback on Unrolled Convolution Case Study

### ISSUE THREAD

**Issue by lisaong** [MarinaHesham/HighPerfDL-Accera-Samples#3]
Looks good, some minor comments below:

https://github.com/marina-neseem/Accera-High-Perf-DL/blob/25b3e7403a9a4639d30c564200097fc47249f36c/case_studies/unrolled_convolution_gridsearch/README.md?plain=1#L33

Comment: [Editorial] probably won't need the underlining for "in the first method" and "in the second method" (I was expecting those to be clickable links). The emphasis is good enough for the "In this case study, we will apply the first method."

https://github.com/marina-neseem/Accera-High-Perf-DL/blob/25b3e7403a9a4639d30c564200097fc47249f36c/case_studies/unrolled_convolution_gridsearch/README.md?plain=1#L67

Comment: input, output, and weights arrays

https://github.com/marina-neseem/Accera-High-Perf-DL/blob/25b3e7403a9a4639d30c564200097fc47249f36c/case_studies/unrolled_convolution_gridsearch/README.md?plain=1#L247

Comment: minor rendering issue with the Note (needs to be moved out of the code block probably)

https://github.com/marina-neseem/Accera-High-Perf-DL/blob/25b3e7403a9a4639d30c564200097fc47249f36c/case_studies/unrolled_convolution_gridsearch/README.md?plain=1#L294

Comment: typo in "We can do ths by..."

**Comment by marina-neseem** [comment]
Thanks a lot for the feedback @lisaong, I made some changes to address your comments
